apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: 2019-02-21T22:02:43Z
  generation: 1
  labels:
    branch: master
    build-number: "1"
    owner: abayer
    repo: js-test-repo
    tekton.dev/pipeline: abayer-js-test-repo-master
  name: abayer-js-test-repo-master-1
  namespace: jx
  ownerReferences:
  - apiVersion: tekton.dev/v1alpha1
    kind: Pipeline
    name: abayer-js-test-repo-master
    uid: 69ec9014-3624-11e9-b776-42010a8a00ac
  resourceVersion: "6344"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/jx/pipelineruns/abayer-js-test-repo-master-1
  uid: 69fb89f5-3624-11e9-b776-42010a8a00ac
spec:
  Status: ""
  params: null
  pipelineRef:
    name: abayer-js-test-repo-master
  resources:
  - name: abayer-js-test-repo-master
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-js-test-repo-master
  - name: temp-ordering-resource
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: temp-ordering-resource
  serviceAccount: tekton-bot
  trigger:
    type: manual
status:
  conditions:
  - lastTransitionTime: 2019-02-21T22:04:24Z
    message: All Tasks have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  startTime: 2019-02-21T22:02:43Z
  taskRuns:
    abayer-js-test-repo-master-1-build-ttvzf:
      conditions:
      - lastTransitionTime: 2019-02-21T22:03:54Z
        status: "True"
        type: Succeeded
      podName: abayer-js-test-repo-master-1-build-ttvzf-pod-937200
      startTime: 2019-02-21T22:02:43Z
      steps:
      - logsURL: ""
        terminated:
          containerID: docker://ed2e0600af698c48c12c02aacdfd76c5a02ca8ebdf9849bc4df1f4c093fa327f
          exitCode: 0
          finishedAt: 2019-02-21T22:03:04Z
          reason: Completed
          startedAt: 2019-02-21T22:03:01Z
      - logsURL: ""
        terminated:
          containerID: docker://8aee17337d7eab04996c91717012e103bfb0510184a3ca20bcab01eb21e4d432
          exitCode: 0
          finishedAt: 2019-02-21T22:03:07Z
          reason: Completed
          startedAt: 2019-02-21T22:03:07Z
      - logsURL: ""
        terminated:
          containerID: docker://a1713f8af2bd6d0ac007f39482feec7206a1d164f5b2c329be267f4836ef110d
          exitCode: 0
          finishedAt: 2019-02-21T22:03:37Z
          reason: Completed
          startedAt: 2019-02-21T22:03:36Z
      - logsURL: ""
        terminated:
          containerID: docker://aaa2a796eb46ab3eae0053a300ce9a0964f81b3b41eadd2b2794873f2617817c
          exitCode: 0
          finishedAt: 2019-02-21T22:03:38Z
          reason: Completed
          startedAt: 2019-02-21T22:03:38Z
      - logsURL: ""
        terminated:
          containerID: docker://68a65e3ca44fd47c149aebd64190273c480b7f83c020bd579d14cd3d25a1ef6b
          exitCode: 0
          finishedAt: 2019-02-21T22:03:40Z
          reason: Completed
          startedAt: 2019-02-21T22:03:40Z
      - logsURL: ""
        terminated:
          containerID: docker://7f9f6a78dd471731997a63013872f617cb0da785bbcca244f9ba2b356296901a
          exitCode: 0
          finishedAt: 2019-02-21T22:03:42Z
          reason: Completed
          startedAt: 2019-02-21T22:03:42Z
    abayer-js-test-repo-master-1-second-9czt5:
      conditions:
      - lastTransitionTime: 2019-02-21T22:04:24Z
        status: "True"
        type: Succeeded
      podName: abayer-js-test-repo-master-1-second-9czt5-pod-62d12d
      startTime: 2019-02-21T22:03:56Z
      steps:
      - logsURL: ""
        terminated:
          containerID: docker://557e7e7571f62c607c854f3ffa654b10f82196101d46f20939829fbdc6a1320e
          exitCode: 0
          finishedAt: 2019-02-21T22:04:07Z
          reason: Completed
          startedAt: 2019-02-21T22:04:07Z
      - logsURL: ""
        terminated:
          containerID: docker://3b4150a8ad7e8c6b171e57188fbfb74ffc794aafaeb6073d5997a46d9d399004
          exitCode: 0
          finishedAt: 2019-02-21T22:04:08Z
          reason: Completed
          startedAt: 2019-02-21T22:04:08Z
      - logsURL: ""
        terminated:
          containerID: docker://c98db7ca8b2ff5566605deddaa22694009fc5f23bdf7a56bb1efa4c92fd0a222
          exitCode: 0
          finishedAt: 2019-02-21T22:04:09Z
          reason: Completed
          startedAt: 2019-02-21T22:04:09Z
      - logsURL: ""
        terminated:
          containerID: docker://130a294841624b138d801306a7bf6923e9d6f18dbb2d161bb9d18107bffc896f
          exitCode: 0
          finishedAt: 2019-02-21T22:04:10Z
          reason: Completed
          startedAt: 2019-02-21T22:04:10Z
      - logsURL: ""
        terminated:
          containerID: docker://712659711fe0dd07add0740d22898207768bfeb823a2dc11b062092a3fbb5110
          exitCode: 0
          finishedAt: 2019-02-21T22:04:11Z
          reason: Completed
          startedAt: 2019-02-21T22:04:11Z
      - logsURL: ""
        terminated:
          containerID: docker://b7dd7d255a48ef595b47206f247d1b49ea33b3aed21c126b24fa1db3a22c91c3
          exitCode: 0
          finishedAt: 2019-02-21T22:04:12Z
          reason: Completed
          startedAt: 2019-02-21T22:04:12Z
