apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: really-long
    build: "1"
    owner: abayer
    jenkins.io/pipelineType: build
    repository: js-test-repo
  name: abayer-js-test-repo-really-long-1
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              tekton.dev/pipelineRun: abayer-js-test-repo-really-long-1
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 100
  params:
  - name: version
    value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: abayer-js-test-repo-really-long-1
  resources:
  - name: abayer-js-test-repo-really-long
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-js-test-repo-really-long
  serviceAccount: tekton-bot
  timeout: 240h0m0s
status: {}
