approve:
- lgtm_acts_as_approve: true
  require_self_approval: true
  repos:
  - jenkins-x
  - jenkins-x-charts
  - jenkins-x-apps
  - jenkinsci
  - cloudbees
blunderbuss: {}
cat: {}
lgtm:
- repos:
  - jenkins-x/jx
  - jenkins-x/jenkins-x-versions
  review_acts_as_lgtm: true
- repos:
  - jenkinsci/jx-resources-plugin
  review_acts_as_lgtm: true
- repos:
  - cloudbees/jxui-backend
  - cloudbees/jxui-frontend
  review_acts_as_lgtm: true
- repos:
  - cloudbees/core-controller
  review_acts_as_lgtm: true
cherry_pick_unapproved: {}
config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
external_plugins:
  jenkins-x/environment-tekton-mole-dev: null
  jenkins-x/environment-tekton-mole-production: null
  jenkins-x/environment-tekton-mole-staging: null
heart:
  adorees:
  - jenkins-x-bot
owners: {}
plugins:
  jenkins-x/prow-config-tekton:
  - config-updater
  - size
  - shrug
  - skip
  - yuks
  cloudbees/jxui-backend:
  - approve
  - assign
  - blunderbuss
  - heart
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  cloudbees/jxui-ts-client:
  - approve
  - assign
  - blunderbuss
  - heart
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  cloudbees/jxui-frontend:
  - approve
  - assign
  - blunderbuss
  - heart
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/jenkins-x-versions:
  - approve
  - assign
  - blunderbuss
  - heart
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/environment-tekton-mole-dev:
  - approve
  - assign
  - blunderbuss
  - heart
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/environment-tekton-mole-production:
  - approve
  - assign
  - blunderbuss
  - heart
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x/environment-tekton-mole-staging:
  - approve
  - assign
  - blunderbuss
  - heart
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  jenkins-x-apps/jx-app-sonarqube:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-cheese:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-grafana:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-datadog:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-istio:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-gitea:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-jenkins:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-anchore:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-ambassador:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-test-lifecycle:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-athens:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  jenkins-x-apps/jx-app-sso:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-cert-manager:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-jacoco:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/hey:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/jenkins-x-minimal:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/nexus:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/tekton:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/openshift-namespace-rbac-chart:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/athens-proxy:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/vault-operator:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/knative-build:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/jx-build-templates:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/environment-controller:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/prow:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-charts/kubernetes-replicator:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x-apps/jx-app-prometheus:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-builders:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-builders-base:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx-datadog:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx-docs:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx-tutorial:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-builders-base-image:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-serverless-filerunner:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-serverless:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/dev-env:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/dev-env-base:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  cloudbees/jx-tenant-service:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/updatebot:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/ext-java-code-quality:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/homebrew-jx:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-image:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jenkins-x-platform:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx-ts-client:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/jx:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/sso-operator:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/exposecontroller:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  jenkins-x/bucketrepo:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
  cloudbees/cb-app-slack:
  - approve
  - heart
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - label
  - size
  - trigger
  - wip
  - cat
  - dog
  - override
requiresig: {}
sigmention: {}
slack: {}
triggers:
- repos:
  - jenkins-x
  - jenkins-x-apps
  - jenkins-x-charts
  - cloudbees
  trusted_org: jenkins-x
  only_org_members: true
welcome:
- message_template: Welcome contributor to Jenkins X
