apiVersion: v1
items:
  - apiVersion: jenkins.io/v1
    kind: SourceRepository
    metadata:
      name: jx-scheduler-test-repo
      namespace: jx
    spec:
      description: Test Repo
      org: cb-kubecd
      provider: https://github.com
      repo: jx-scheduler-test-repo
      scheduler:
        apiVersion: jenkins.io/v1
        kind: Scheduler
        name: jx-repo-scheduler
  - apiVersion: jenkins.io/v1
    kind: SourceRepository
    metadata:
      name: jx-scheduler-group-test-repo
      namespace: jx
    spec:
      description: Test Group Repo
      org: cb-kubecd
      provider: https://github.com
      repo: jx-scheduler-test-group-repo
      scheduler:
        apiVersion: jenkins.io/v1
        kind: Scheduler
        name: jx-repo-group-scheduler
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
