extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-nodejs
  container: nodejs
pipelines:
  pullRequest:
    build:
      steps:
        - sh: npm install
          name: npm-install
        - sh: CI=true DISPLAY=:99 npm test
  release:
    setVersion:
      steps:
        - sh: echo \$(jx-release-version) > VERSION
          name: next-version
          comment: so we can retrieve the version in later steps
        # TODO modify package.json?
        - sh: jx step tag --version \$(cat VERSION)
          name: tag-version
    build:
      steps:
        - sh: npm install
          name: npm-install
        - sh: CI=true DISPLAY=:99 npm test
          name: npm-test
