apiVersion: tekton.dev/v1alpha1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    creationTimestamp: "2019-09-10T17:07:08Z"
    generation: 1
    labels:
      branch: master
      build: "1"
      created-by-prow: "true"
      owner: cb-kubecd
      jenkins.io/pipelineType: meta
      prowJobName: 6bae4c2b-d3ed-11e9-b0c6-72256f93bb5c
      repository: bdd-spring-1568135191
    name: meta-cb-kubecd-bdd-spring-15681-1
    namespace: jx
    ownerReferences:
    - apiVersion: jenkins.io/v1
      kind: PipelineActivity
      name: cb-kubecd-bdd-spring-1568135191-master-1
      uid: 6c3963df-d3ed-11e9-8142-42010a840094
    resourceVersion: "3188"
    selfLink: /apis/tekton.dev/v1alpha1/namespaces/jx/pipelines/meta-cb-kubecd-bdd-spring-15681-1
    uid: 6c431e3c-d3ed-11e9-8142-42010a840094
  spec:
    resources:
    - name: meta-cb-kubecd-bdd-spring-15681
      type: git
    tasks:
    - name: meta-pipeline
      resources:
        inputs:
        - name: workspace
          resource: meta-cb-kubecd-bdd-spring-15681
      taskRef:
        name: meta-cb-kubecd-bdd-spring-15681-meta-pipeline-1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
