apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    owner: abayer
    jenkins.io/pipelineType: build
    repository: jx-demo-qs
  name: abayer-jx-demo-qs-master-1
spec:
  params:
  - name: version
    value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: abayer-jx-demo-qs-master-1
  resources:
  - name: abayer-jx-demo-qs-master
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-jx-demo-qs-master
  serviceAccount: tekton-bot
  timeout: 240h0m0s
status: {}
