apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    jenkins.io/last-build-number: "1"
  creationTimestamp: 2019-02-21T22:07:36Z
  generation: 1
  name: abayer-js-test-repo-nested
  namespace: jx
  resourceVersion: "6988"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/jx/pipelines/abayer-js-test-repo-nested
  uid: 18a97245-3625-11e9-b776-42010a8a00ac
spec:
  params: null
  resources:
  - name: abayer-js-test-repo-nested
    type: git
  - name: temp-ordering-resource
    type: image
  tasks:
  - name: build
    resources:
      inputs:
      - name: workspace
        resource: abayer-js-test-repo-nested
      - name: temp-ordering-resource
        resource: temp-ordering-resource
      outputs:
      - name: workspace
        resource: abayer-js-test-repo-nested
      - name: temp-ordering-resource
        resource: temp-ordering-resource
    taskRef:
      name: abayer-js-test-repo-nested-build
  - name: second
    resources:
      inputs:
      - from:
        - build
        name: workspace
        resource: abayer-js-test-repo-nested
      - from:
        - build
        name: temp-ordering-resource
        resource: temp-ordering-resource
      outputs:
      - name: workspace
        resource: abayer-js-test-repo-nested
      - name: temp-ordering-resource
        resource: temp-ordering-resource
    taskRef:
      name: abayer-js-test-repo-nested-second
