apiVersion: jenkins.io/v1
kind: PipelineStructure
metadata:
  creationTimestamp: 2019-02-21T22:07:37Z
  generation: 1
  name: abayer-js-test-repo-nested-1
  namespace: jx
  ownerReferences:
  - apiVersion: tekton.dev/v1alpha1
    kind: Pipeline
    name: abayer-js-test-repo-nested
    uid: 18a97245-3625-11e9-b776-42010a8a00ac
  resourceVersion: "6994"
  selfLink: /apis/jenkins.io/v1/namespaces/jx/pipelinestructures/abayer-js-test-repo-nested-1
  uid: 19001dd4-3625-11e9-b776-42010a8a00ac
pipelineRef: abayer-js-test-repo-nested
pipelineRunRef: abayer-js-test-repo-nested-1
stages:
- depth: 0
  name: Parent
  stages:
  - Build
  - Second
- depth: 1
  name: Build
  parent: Parent
  taskRef: abayer-js-test-repo-nested-build
- depth: 1
  name: Second
  parent: Parent
  previous: Build
  taskRef: abayer-js-test-repo-nested-second
