apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    creationTimestamp: 2019-02-21T22:07:36Z
    generation: 1
    labels:
      jenkins.io/task-stage-name: build
    name: abayer-js-test-repo-nested-build
    namespace: jx
    resourceVersion: "6978"
    selfLink: /apis/tekton.dev/v1alpha1/namespaces/jx/tasks/abayer-js-test-repo-nested-build
    uid: 188b1ca9-3625-11e9-b776-42010a8a00ac
  spec:
    inputs:
      resources:
      - name: workspace
        targetPath: workspace
        type: git
      - name: temp-ordering-resource
        targetPath: ""
        type: image
    outputs:
      resources:
      - name: workspace
        targetPath: ""
        type: git
      - name: temp-ordering-resource
        targetPath: ""
        type: image
    steps:
    - args:
      - echo hello world
      command:
      - /bin/sh
      - -c
      env:
      - name: DOCKER_REGISTRY
        value: 10.3.245.235:5000
      - name: PIPELINE_KIND
        value: release
      - name: REPO_OWNER
        value: abayer
      - name: REPO_NAME
        value: js-test-repo
      - name: JOB_NAME
        value: abayer/js-test-repo/nested
      - name: BRANCH_NAME
        value: nested
      - name: JX_BATCH_MODE
        value: "true"
      image: jenkinsxio/builder-nodejs:0.1.235
      name: step2
      resources:
        requests:
          cpu: 400m
          memory: 512Mi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /home/jenkins
        name: workspace-volume
      - mountPath: /var/run/docker.sock
        name: docker-daemon
      - mountPath: /home/jenkins/.docker
        name: volume-0
      - mountPath: /etc/podinfo
        name: podinfo
        readOnly: true
      workingDir: /workspace/workspace
    - args:
      - ls -la
      command:
      - /bin/sh
      - -c
      env:
      - name: DOCKER_REGISTRY
        value: 10.3.245.235:5000
      - name: PIPELINE_KIND
        value: release
      - name: REPO_OWNER
        value: abayer
      - name: REPO_NAME
        value: js-test-repo
      - name: JOB_NAME
        value: abayer/js-test-repo/nested
      - name: BRANCH_NAME
        value: nested
      - name: JX_BATCH_MODE
        value: "true"
      image: jenkinsxio/builder-nodejs:0.1.235
      name: step3
      resources:
        requests:
          cpu: 400m
          memory: 512Mi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /home/jenkins
        name: workspace-volume
      - mountPath: /var/run/docker.sock
        name: docker-daemon
      - mountPath: /home/jenkins/.docker
        name: volume-0
      - mountPath: /etc/podinfo
        name: podinfo
        readOnly: true
      workingDir: /workspace/workspace
    - args:
      - sleep 5
      command:
      - /bin/sh
      - -c
      env:
      - name: DOCKER_REGISTRY
        value: 10.3.245.235:5000
      - name: PIPELINE_KIND
        value: release
      - name: REPO_OWNER
        value: abayer
      - name: REPO_NAME
        value: js-test-repo
      - name: JOB_NAME
        value: abayer/js-test-repo/nested
      - name: BRANCH_NAME
        value: nested
      - name: JX_BATCH_MODE
        value: "true"
      image: jenkinsxio/builder-nodejs:0.1.235
      name: step4
      resources:
        requests:
          cpu: 400m
          memory: 512Mi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /home/jenkins
        name: workspace-volume
      - mountPath: /var/run/docker.sock
        name: docker-daemon
      - mountPath: /home/jenkins/.docker
        name: volume-0
      - mountPath: /etc/podinfo
        name: podinfo
        readOnly: true
      workingDir: /workspace/workspace
    volumes:
    - emptyDir: {}
      name: workspace-volume
    - hostPath:
        path: /var/run/docker.sock
      name: docker-daemon
    - name: volume-0
      secret:
        secretName: jenkins-docker-cfg
    - downwardAPI:
        items:
        - fieldRef:
            fieldPath: metadata.labels
          path: labels
      name: podinfo
- apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    creationTimestamp: 2019-02-21T22:07:36Z
    generation: 1
    labels:
      jenkins.io/task-stage-name: second
    name: abayer-js-test-repo-nested-second
    namespace: jx
    resourceVersion: "6979"
    selfLink: /apis/tekton.dev/v1alpha1/namespaces/jx/tasks/abayer-js-test-repo-nested-second
    uid: 189bd03f-3625-11e9-b776-42010a8a00ac
  spec:
    inputs:
      resources:
      - name: workspace
        targetPath: ""
        type: git
      - name: temp-ordering-resource
        targetPath: ""
        type: image
    outputs:
      resources:
      - name: workspace
        targetPath: ""
        type: git
      - name: temp-ordering-resource
        targetPath: ""
        type: image
    steps:
    - args:
      - echo hi everybody
      command:
      - /bin/sh
      - -c
      env:
      - name: DOCKER_REGISTRY
        value: 10.3.245.235:5000
      - name: PIPELINE_KIND
        value: release
      - name: REPO_OWNER
        value: abayer
      - name: REPO_NAME
        value: js-test-repo
      - name: JOB_NAME
        value: abayer/js-test-repo/nested
      - name: BRANCH_NAME
        value: nested
      - name: JX_BATCH_MODE
        value: "true"
      image: jenkinsxio/builder-nodejs:0.1.235
      name: step2
      resources:
        requests:
          cpu: 400m
          memory: 512Mi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /home/jenkins
        name: workspace-volume
      - mountPath: /var/run/docker.sock
        name: docker-daemon
      - mountPath: /home/jenkins/.docker
        name: volume-0
      - mountPath: /etc/podinfo
        name: podinfo
        readOnly: true
      workingDir: /workspace/workspace
    - args:
      - sleep 5
      command:
      - /bin/sh
      - -c
      env:
      - name: DOCKER_REGISTRY
        value: 10.3.245.235:5000
      - name: PIPELINE_KIND
        value: release
      - name: REPO_OWNER
        value: abayer
      - name: REPO_NAME
        value: js-test-repo
      - name: JOB_NAME
        value: abayer/js-test-repo/nested
      - name: BRANCH_NAME
        value: nested
      - name: JX_BATCH_MODE
        value: "true"
      image: jenkinsxio/builder-nodejs:0.1.235
      name: step3
      resources:
        requests:
          cpu: 400m
          memory: 512Mi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /home/jenkins
        name: workspace-volume
      - mountPath: /var/run/docker.sock
        name: docker-daemon
      - mountPath: /home/jenkins/.docker
        name: volume-0
      - mountPath: /etc/podinfo
        name: podinfo
        readOnly: true
      workingDir: /workspace/workspace
    volumes:
    - emptyDir: {}
      name: workspace-volume
    - hostPath:
        path: /var/run/docker.sock
      name: docker-daemon
    - name: volume-0
      secret:
        secretName: jenkins-docker-cfg
    - downwardAPI:
        items:
        - fieldRef:
            fieldPath: metadata.labels
          path: labels
      name: podinfo
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
