approve:
- lgtm_acts_as_approve: true
  repos:
  - acme/dummy
  ignore_review_state: false
#blunderbuss: {}
#cat: {}
#cherry_pick_unapproved: {}
#config_updater:
#  maps:
#    prow/config.yaml:
#      name: config
#    prow/plugins.yaml:
#      name: plugins
external_plugins:
  acme/dummy:
  - endpoint: http://jx-app-cheese
    name: jx-app-cheese
#heart: {}
#owners: {}
plugins:
  acme/dummy:
    - cat
    - help
    - hold
    - lgtm
    - lifecycle
    - trigger
    - wip
    - heart
    - override
#requiresig: {}
#sigmention: {}
#slack: {}
triggers:
- repos:
  - acme/dummy
  trusted_org: roadrunner-corp
  join_org_url: http://org-url
  only_org_members: true
  ignore_ok_to_test: true
#welcome:
#- message_template: Welcome

lgtm:
  - review_acts_as_lgtm: true
    store_tree_hash: true
    trusted_team_for_sticky_lgtm: team2
    repos:
      - acme/dummy